#753 Super critical exception workaround.
RedDuck-Software/Badaboom pull request #16
Opened 2022-06-30 13:09 UTC by ArtemBuryko

Wrapped into the try-attempt loop with 20 sec delay between

2022-07-01 08:38 UTC, borseno requested changes

2022-07-01 08:38 UTC, borseno commented on Indexing.Core/Indexer.cs
> +                }
maybe use Task.Delay to avoid throttling threads?

2022-07-01 08:38 UTC, borseno commented on Indexing.Core/Indexer.cs
> +                            System.Threading.Thread.Sleep(DelayAttempts * 1000);
same comment as above, we should use System.Task.Delay vs Thread.Sleep in async functions. or explain why this is used here?

2022-07-01 08:38 UTC, borseno commented on Indexing.Core/Indexer.cs
> +                        System.Threading.Thread.Sleep(DelayAttempts * 1000);
same comment as above, we should use Task.Delay vs Thread.Sleep in async functions.

2022-07-01 08:38 UTC, borseno commented on Indexing.Core/Indexer.cs
> +                catch (Exception ex) // if exception wasn`t handled in IndexBlock method - this is a Rpc call Exception
It seems that this code is repeating, could you extract repeating code into a common function to keep the code DRY.

2022-07-01 08:38 UTC, borseno commented on Indexing.Core/Indexer.cs
> +                        System.Threading.Thread.Sleep(DelayAttempts * 1000);
Same comment as above - please look at all the changes and make sure they comply with the comments made earlier

2022-07-04 11:25 UTC, borseno requested changes

2022-07-04 12:45 UTC, ArtemBuryko commented on Indexing.Core/Indexer.cs
> +        private async void ThrowOrDelay(int attempts, Exception ex)
fixed

2022-07-05 13:32 UTC, merged